  ##security.require_ssl: true
server: ## Config Web Server
   port: 20001
   contextPath: /cache-server
   tomcat:
      access_log_enabled: true
      basedir: target/tomcat
      
spring:
   application.name : cache-server
   boot.admin: #Spring Boot Admin Config    
      url: http://localhost:18100/
      username: operations
      password: changeIt!
      client.metadata.user.name: ${spring.boot.admin.username}
      client.metadata.user.password: ${spring.boot.admin.password}
      
management.security.enabled: false
security:
   basic.enabled: false
#hawtio:
#   authenticationEnabled: false
#   hawtio.offline: true
            
## LOGGING CONF
logging:
   path: ./target/ 
   file: ${spring.application.name}
   level:
      com.minsait: DEBUG
      org.springframework.boot: INFO
#      org.springframework.boot.autoconfigure: DEBUG