#Integration Resources docker
onesaitplatform:
  urls: 
    domain:
      base: https://s4citiespro.westeurope.cloudapp.azure.com/
    digitalTwinBroker:
      base: http://digitaltwinbrokerservice:19300/digitaltwinbroker
    controlpanel:
      base: https://s4citiespro.westeurope.cloudapp.azure.com/controlpanel
    iotbroker:
      base: http://iotbrokerservice:19000/iot-broker
      advice: http://iotbrokerservice:19000/iot-broker/advice
    scriptingEngine:
      base:
      advice:
    flowEngine:
      base: https://s4citiespro.westeurope.cloudapp.azure.com/flowengine/
      advice: https://s4citiespro.westeurope.cloudapp.azure.com/nodered/
    routerStandAlone:
      base: https://routerservice:20000/router
      advice: http://routerservice:20000/router/router/advice/
      management: http://routerservice:20000/router/management/
      router: http://routerservice:20000/router/router/
      hawtio: http://s4citiespro.westeurope.cloudapp.azure.com/hawtio/index.html
      swaggerUI: http://s4citiespro.westeurope.cloudapp.azure.com/router/swagger-ui.html
    apiManager:
      base: https://s4citiespro.westeurope.cloudapp.azure.com/api-manager/
      api: https://s4citiespro.westeurope.cloudapp.azure.com/api-manager/server/api/
      swaggerUI: https://s4citiespro.westeurope.cloudapp.azure.com/api-manager/swagger-ui.html?url=
      swaggerUIManagement: https://s4citiespro.westeurope.cloudapp.azure.com/api-manager/services/management/api-docs?url=/api-manager/services/management/swagger.json
      swaggerJson: https://s4citiespro.westeurope.cloudapp.azure.com/api-manager/services/management/swagger/
