# Gmail Config for SMTP
mail:
  host: smtp.gmail.com
  port: 587
  username: select4citiesminsait@gmail.com
  password: Select4cities2018!
  smtp:
     auth: true
     starttls_enable: true
     starttls_required: true
     timeout: 5000
     connectiontimeout: 5000
     writetimeout: 5000 