onesaitplatform:
  env:
    database:
      queries-limit: 2000
      mongodb-quasar-timeout: 10000
      mongodb-quasar-compile: true
      elastic-sql-timeout: 10000
    files:
      max-size: !!java.lang.Long 60000000
    iotbroker:
      session-expiration: !!java.lang.Long 600000
    audit:
      ignore: false