onesaitplatform:
   flowengine:
      node.path: node
      launcher:
         path: /opt/nodeRed/Flow-Engine-Manager
   database.mongodb:
      servers: ${REALTIMEDBSERVERS} 
      quasar.connector.http.endpoint: http://${QUASARHOST}:${QUASARPORT}/query/fs/ 
      authenticationDatabase: ${REALTIMEDBAUTHDB}       
      useAuth: ${REALTIMEDBUSEAUTH}
      username: ${REALTIMEDBUSER}
      password: ${REALTIMEDBPASS}
      writeConcern: ${REALTIMEDBWRITECONCERN}                 
   database.elasticsearch:
      sql.connector.http.endpoint: http://${ELASTICDBHOST}:${ELASTICDBPORT}
      url: ${ELASTICDBHOST} 
      port: 9300        
   router.alternativeURL: http://routerservice:20000/router/router/
spring:
   datasource:  
      url: jdbc:mysql://${CONFIGDBHOST}:${CONFIGDBPORT}/onesaitplatform_config?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&autoReconnect=true
      driver-class-name: com.mysql.jdbc.Driver
      test-while-idle: true
      test-on-borrow: true
      validation-query: SELECT 1   
   boot.admin: #Spring Boot Admin Config    
      url: http://monitoringuiservice:18100/monitoring
      client.service-url: http://flowengineservice:${server.port}${server.contextPath}/ 
   data.mongodb:
      host: ${REALTIMEDBSERVERS}
   elasticsearch.jest:
      uris: http://${ELASTICDBHOST}:${ELASTICDBPORT}                
quartz:
    datasource:
      url: jdbc:mysql://${SCHEDULERDBHOST}:${SCHEDULERDBPORT}/onesaitplatform_scheduler?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&autoReconnect=true
## LOGGING CONF
logging:
   path: /var/log/platform-logs 