onesaitplatform: #Config onesaitplatform specific
   iotbroker.plugable:
      gateway:
         kafka:
            enable: ${KAFKAENABLED}
            host: ${KAFKAHOST}
            port: ${KAFKAPORT}
   database.elasticsearch:
      sql.connector.http.endpoint: http://${ELASTICDBHOST}:${ELASTICDBPORT}
      url: ${ELASTICDBHOST}
   database.mongodb:
      servers: ${REALTIMEDBSERVERS}
      authenticationDatabase: ${REALTIMEDBAUTHDB}      
      useAuth: ${REALTIMEDBUSEAUTH}
      username: ${REALTIMEDBUSER}
      password: ${REALTIMEDBPASS} 
      writeConcern: ${REALTIMEDBWRITECONCERN}      
      quasar.connector.http.endpoint: http://${QUASARHOST}:${QUASARPORT}/query/fs/ 
   
spring: ## General Config  
   boot.admin: #Spring Boot Admin Config    
      url: http://monitoringuiservice:18100/monitoring    
      client.service-url: http://routerservice:${server.port}${server.contextPath}/ 
   datasource: ## JPA Config
      url: jdbc:mysql://${CONFIGDBHOST}:${CONFIGDBPORT}/onesaitplatform_config?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&autoReconnect=true
   data.mongodb:
      host: ${REALTIMEDBSERVERS}      
   elasticsearch.jest:
      uris: http://${ELASTICDBHOST}:${ELASTICDBPORT}      
            
## LOGGING CONF
logging:
   path: /var/log/platform-logs
   level:
      com.minsait: DEBUG