## Config Web Server
server:
   port: 24000
   contextPath: /video-broker

management.security.enabled: false
spring:
  application.name: onesaitplatform-video-broker
  boot.admin: #Spring Boot Admin Config    
      url: http://localhost:18100/
      username: operations
      password: changeIt!
      client.metadata.user.name: ${spring.boot.admin.username}
      client.metadata.user.password: ${spring.boot.admin.password}
  datasource: ## JPA Config
      url: jdbc:mysql://localhost:3306/onesaitplatform_config?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&autoReconnect=true
      username: root
      password: changeIt!
      driver-class-name: com.mysql.jdbc.Driver
      test-while-idle: true
      test-on-borrow: true
      validation-query: SELECT 1      
      tomcat:
         # Number of ms to wait before throwing an exception if no connection is available.
         max-wait: 10000
         # Maximum number of active connections that can be allocated from this pool at the same time.
         max-active: 50
         # Validate the connection before borrowing it from the pool.
         test-on-borrow: true
  jpa:
      # The SQL dialect makes Hibernate generate better SQL for the chosen database
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      # Hibernate ddl auto (create, create-drop, validate, update)
      hibernate.ddl-auto: validate
      hibernate.temp.use_jdbc_metadata_defaults: false
      show-sql: false
      properties.hibernate.format_sql: true
      properties.hibernate.temp.use_jdbc_metadata_defaults: false

onesaitplatform:
  videobroker:
    path:
       processor-resources: /usr/local/app/resources/
      # processor-resources: /Users/javi/openplatform/onesait-cloud/onesait-cloud-platform/sources/modules/video-broker/docker/resources/
    threading:
       core-pool-size: 10
       max-pool-size: 25
       queue-capacity: 100
       name-prefix: video_broker
    hazelcast.queue: videoQueue
  kafka:
        enable: false
        host: development.onesaitplatform.com
        port: 9095
        user: VideoBrokerClient
        password: 54986d1088d24dd48605a93e85665e1c
        partitions: 4
        replication: 1
        prefix: ONTOLOGY_
        group: ontologyGroup
        topic.pattern: ontology.*
        router.topic: router
        consumer.consumersCount : 10
        consumer.seekTo : beginning 
        consumer.group : kafkaGroup
        consumer.maxPollRecords : 200
        consumer.maxAge : 5000

## LOGGING CONF
logging:
   config: classpath:logback-spring.xml
   path: ./target/ 
   file: ${spring.application.name}
   level:
      com.minsait: INFO 
      org.springframework.boot: INFO


