version: "2.1"
services:
  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"      
    volumes:  
      - ${HOST_VOLUME_NGINX}/nginx.conf:/etc/nginx/nginx.conf:rw
      - ${HOST_VOLUME_NGINX}/domain.crt:/etc/nginx/ssl/domain.crt:ro
      - ${HOST_VOLUME_NGINX}/domain.key:/etc/nginx/ssl/domain.key:ro       
    restart: on-failure 
    links:
      - rancherinstance 
    networks:
      - datanetwork          
  rancherinstance:
    image: rancher/rancher:latest
    container_name: rancherinstance
    ports:
      - "9080:8080"
    volumes:
      - ${HOST_VOLUME_PERSIST}:/var/lib/rancher
    networks:
      - datanetwork     
networks:
  datanetwork:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
