---
# Create directories and give permissions

- name: Create configdb directory
  file: path="{{ root_directory }}/onesaitplatform/configdb" state=directory
  
- name: Create schedulerdb directory
  file: path="{{ root_directory }}/onesaitplatform/schedulerdb" state=directory  
  
- name: Create realtimedb directory
  file: path="{{ root_directory }}/onesaitplatform/realtimedb" state=directory mode=777
  
- name: Create elasticdb directory
  file: path="{{ root_directory }}/onesaitplatform/elasticdb" state=directory mode=777     
  
- name: Create platform-logs directory
  file: path="{{ root_directory }}/onesaitplatform/platform-logs" state=directory mode=777
  
- name: Create notebooks directories - step 1
  file: path="{{ root_directory }}/onesaitplatform/zeppelin/interpreter" state=directory
  
- name: Create notebooks directories - step 2
  file: path="{{ root_directory }}/onesaitplatform/zeppelin/notebook" state=directory  
  
- name: Create notebooks directories - step 3
  file: path="{{ root_directory }}/onesaitplatform/zeppelin/conf" state=directory      
  
- name: Create web projects directories
  file: path="{{ root_directory }}/onesaitplatform/webprojects" state=directory mode=777

- name: Create streamsets directories - step 1
  file: path="{{ root_directory }}/onesaitplatform/streamsets" state=directory mode=777

- name: Create streamsets directories - step 2
  file: path="{{ root_directory }}/onesaitplatform/streamsets/data" state=directory mode=777

- name: Increase virtual machine max map count
  command: sysctl -w vm.max_map_count=262144
  
- name: Create nginx directory
  file: path="{{ root_directory }}/onesaitplatform/nginx/certs" state=directory     
  
- name: Create kafka logs directory
  file: path="{{ root_directory }}/onesaitplatform/kafka-logs" state=directory 
  
- name: Create flowengine directory
  file: path="{{ root_directory }}/onesaitplatform/flowengine" state=directory mode=777

- name: Create rancher compose directory
  file: path="{{ root_directory }}/onesaitplatform/rancher" state=directory
    
- name: Create rancherdata directory
  file: path="{{ root_directory }}/onesaitplatform/rancher/data" state=directory

- name: Create platform compose directory
  file: path="{{ root_directory }}/onesaitplatform/rancher/platform_compose" state=directory

- name: Create self signed certificate using OpenSSL
  command: openssl req \
           -new \
           -newkey rsa:4096 \
           -days 365 \
           -nodes \
           -x509 \
           -subj '/C=ES/ST=Minsait/L=Madrid/O=Indra/CN={{ fqdn_server_name }}' \
           -keyout {{ self_signed_certs_key }} \
           -out {{ self_signed_certs_cert }} 
