version: '2'
services:
  oauthservice:
    image: registry.onesaitplatform.com/onesaitplatform/oauthserver:{{ onesait_version }}
    environment:
      SERVER_NAME: {{ fqdn_server_name }}
    stdin_open: true
    volumes:
    - {{ root_directory }}/onesaitplatform/platform-logs:/var/log/platform-logs:rw
    tty: true
    links:
    - configdb:configdb
    ports:
    - 21000:21000/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: node=MASTER
  kafkamonitoringservice:
    image: registry.onesaitplatform.com/onesaitplatform/burrow:latest
    environment:
      SERVER_NAME: {{ fqdn_server_name }}
      ZOOKEEPER_SERVER: zookeeper
    stdin_open: true
    network_mode: host
    tty: true
    links:
    - zookeeper:zookeeper
    - kafka:kafka
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: node=MASTER
  streamsets:
    image: registry.onesaitplatform.com/onesaitplatform/streamsets:{{ streamsets_version }}
    stdin_open: true
    volumes:
    - {{ root_directory }}/onesaitplatform/streamsets/data:/data:rw
    tty: true
    ports:
    - 18630:18630/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: node=MASTER
  schedulerdb:
    privileged: true
    image: registry.onesaitplatform.com/onesaitplatform/schedulerdb:{{ scheduler_version }}
    stdin_open: true
    volumes:
    - {{ root_directory }}/onesaitplatform/schedulerdb:/var/lib/mysql:rw
    tty: true
    ports:
    - 3307:3306/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: node=MASTER
  configinit:
    image: registry.onesaitplatform.com/onesaitplatform/configinit:{{ onesait_version }}
    environment:
      LOADMONGODB: 'false'
    stdin_open: true
    tty: true
    links:
    - configdb:configdb
    - realtimedb:realtimedb
    - elasticdb:elasticdb
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: node=MASTER
  apimanagerservice:
    privileged: true
    image: registry.onesaitplatform.com/onesaitplatform/apimanager:{{ onesait_version }}
    environment:
      SERVER_NAME: {{ fqdn_server_name }}
    stdin_open: true
    volumes:
    - {{ root_directory }}/onesaitplatform/platform-logs:/var/log/platform-logs:rw
    tty: true
    links:
    - configdb:configdb
    - cacheservice:cacheservice
    - realtimedb:realtimedb
    - monitoringuiservice:monitoringuiservice
    - schedulerdb:schedulerdb
    - routerservice:routerservice
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: node=MASTER
  digitaltwinbrokerservice:
    image: registry.onesaitplatform.com/onesaitplatform/digitaltwin:{{ onesait_version }}
    environment:
      SERVER_NAME: {{ fqdn_server_name }}
    stdin_open: true
    volumes:
    - {{ root_directory }}/onesaitplatform/platform-logs:/var/log/platform-logs:rw
    tty: true
    links:
    - configdb:configdb
    - monitoringuiservice:monitoringuiservice
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: node=MASTER
  cacheservice:
    privileged: true
    image: registry.onesaitplatform.com/onesaitplatform/cacheservice:{{ onesait_version }}
    stdin_open: true
    volumes:
    - {{ root_directory }}/onesaitplatform/platform-logs:/var/log/platform-logs:rw
    tty: true
    links:
    - controlpanelservice:controlpanelservice
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: node=MASTER
  flowengineservice:
    privileged: true
    image: registry.onesaitplatform.com/onesaitplatform/flowengine:{{ onesait_version }}
    environment:
      SERVERNAME: {{ fqdn_server_name }}
    stdin_open: true
    volumes:
    - {{ root_directory }}/onesaitplatform/flowengine:/tmp:rw
    - {{ root_directory }}/onesaitplatform/platform-logs:/var/log/platform-logs:rw
    tty: true
    links:
    - configdb:configdb
    - quasar:quasar
    - realtimedb:realtimedb
    - monitoringuiservice:monitoringuiservice
    - schedulerdb:schedulerdb
    - routerservice:routerservice
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: node=MASTER
  controlpanelservice:
    privileged: true
    image: registry.onesaitplatform.com/onesaitplatform/controlpanel:{{ onesait_version }}
    environment:
      KAFKAENABLED: 'true'
      SERVER_NAME: {{ fqdn_server_name }}
    volumes:
    - {{ root_directory }}/onesaitplatform/platform-logs:/var/log/platform-logs:rw
    - {{ root_directory }}/onesaitplatform/webprojects:/usr/local/webprojects
    links:
    - configdb:configdb
    - cacheservice:cacheservice
    - quasar:quasar
    - realtimedb:realtimedb
    - elasticdb:elasticdb
    - monitoringuiservice:monitoringuiservice
    - schedulerdb:schedulerdb
    - routerservice:routerservice
    ports:
    - 18000:18000/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: node=MASTER
  elasticdb:
    privileged: true
    image: registry.onesaitplatform.com/onesaitplatform/elasticdb:{{ elastic_version }}
    stdin_open: true
    volumes:
    - {{ root_directory }}/onesaitplatform/elasticdb:/usr/share/elasticsearch/data:rw
    tty: true
    ports:
    - 9200:9200/tcp
    - 9300:9300/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: node=MASTER
  zookeeper:
    privileged: true
    image: registry.onesaitplatform.com/onesaitplatform/zookeeper-secured:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: '2182'
    stdin_open: true
    network_mode: host
    tty: true
    labels:
      io.rancher.scheduler.affinity:host_label: node=MASTER
      io.rancher.container.dns: 'true'
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
  devicesimulator:
    privileged: true
    image: registry.onesaitplatform.com/onesaitplatform/devicesimulator:{{ onesait_version }}
    environment:
      SERVER_NAME: {{ fqdn_server_name }}
    stdin_open: true
    volumes:
    - {{ root_directory }}/onesaitplatform/platform-logs:/var/log/platform-logs:rw
    tty: true
    links:
    - configdb:configdb
    - realtimedb:realtimedb
    - schedulerdb:schedulerdb
    - routerservice:routerservice
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: node=MASTER
  zeppelin:
    privileged: true
    image: registry.onesaitplatform.com/onesaitplatform/notebook:{{ notebook_version }}
    stdin_open: true
    volumes:
    - {{ root_directory }}/onesaitplatform/zeppelin/notebook:/zeppelin/notebook:rw
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: node=MASTER
  configdb:
    privileged: true
    image: registry.onesaitplatform.com/onesaitplatform/configdb:{{ configdb_version }}
    stdin_open: true
    volumes:
    - {{ root_directory }}/onesaitplatform/configdb:/var/lib/mysql:rw
    tty: true
    ports:
    - 3306:3306/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: node=MASTER
  rtdbmaintainerservice:
    image: registry.onesaitplatform.com/onesaitplatform/rtdbmaintainer:{{ onesait_version }}
    environment:
      SERVER_NAME: {{ fqdn_server_name }}
    stdin_open: true
    volumes:
    - {{ root_directory }}/onesaitplatform/platform-logs:/var/log/platform-logs:rw
    - {{ root_directory }}/onesaitplatform/export:/tmp/export:rw
    tty: true
    links:
    - configdb:configdb
    - realtimedb:realtimedb
    - elasticdb:elasticdb
    - schedulerdb:schedulerdb
    - routerservice:routerservice
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: node=MASTER
  iotbrokerservice:
    privileged: true
    image: registry.onesaitplatform.com/onesaitplatform/iotbroker:{{ onesait_version }}
    environment:
      KAFKAENABLED: 'true'
      SERVER_NAME: {{ fqdn_server_name }}
    stdin_open: true
    volumes:
    - {{ root_directory }}/onesaitplatform/platform-logs:/var/log/platform-logs:rw
    tty: true
    links:
    - configdb:configdb
    - realtimedb:realtimedb
    - elasticdb:elasticdb
    - monitoringuiservice:monitoringuiservice
    - kafka:kafka
    - schedulerdb:schedulerdb
    - routerservice:routerservice
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: node=MASTER
  loadbalancerservice:
    privileged: true
    image: nginx:latest
    environment:
      SERVER_NAME: {{ fqdn_server_name }}
    stdin_open: true
    volumes:
    - {{ root_directory }}/onesaitplatform/webprojects:/usr/local/webprojects:rw
    - {{ root_directory }}/onesaitplatform/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - {{ root_directory }}/onesaitplatform/nginx/certs:/etc/nginx/ssl:ro
    - {{ root_directory }}/geo-data:/tmp/geo-data:ro
    tty: true
    links:
    - iotbrokerservice:iotbrokerservice
    - monitoringuiservice:monitoringuiservice
    - controlpanelservice:controlpanelservice
    - flowengineservice:flowengineservice
    - dashboardengineservice:dashboardengineservice
    - apimanagerservice:apimanagerservice
    ports:
    - 80:80/tcp
    - 443:443/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: node=MASTER
  quasar:
    privileged: true
    image: registry.onesaitplatform.com/onesaitplatform/quasar:{{ quasar_version }}
    environment:
      AUTHDB: admin
      AUTHPARAMS: platformadmin:0pen-platf0rm-2018!@
    stdin_open: true
    tty: true
    links:
    - realtimedb:realtimedb
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: node=MASTER
  kafka:
    privileged: true
    image: registry.onesaitplatform.com/onesaitplatform/kafka-secured:{{ kafka_version }}
    hostname: onesait
    environment:
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://0.0.0.0:9095,PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      SERVER_NAME: {{ fqdn_server_name }}
    stdin_open: true
    network_mode: host
    tty: true
    links:
    - zookeeper:zookeeper
    - controlpanelservice:controlpanelservice
    labels:
      io.rancher.scheduler.affinity:host_label: node=MASTER
      io.rancher.container.dns: 'true'
      io.rancher.container.pull_image: always
  monitoringuiservice:
    privileged: true
    image: registry.onesaitplatform.com/onesaitplatform/monitoringui:{{ onesait_version }}
    environment:
      SERVER_NAME: {{ fqdn_server_name }}
    stdin_open: true
    volumes:
    - {{ root_directory }}/onesaitplatform/platform-logs:/var/log/platform-logs:rw
    tty: true
    links:
    - realtimedb:realtimedb
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: node=MASTER
  haproxy:
    image: rancher/lb-service-haproxy:v0.9.3
    ports:
    - 1883:1883/tcp
    - 8883:8883/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: node=MASTER
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
  dashboardengineservice:
    privileged: true
    image: registry.onesaitplatform.com/onesaitplatform/dashboard:{{ onesait_version }}
    environment:
      SERVER_NAME: {{ fqdn_server_name }}
    stdin_open: true
    volumes:
    - {{ root_directory }}/onesaitplatform/platform-logs:/var/log/platform-logs:rw
    tty: true
    links:
    - configdb:configdb
    - quasar:quasar
    - realtimedb:realtimedb
    - monitoringuiservice:monitoringuiservice
    - routerservice:routerservice
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: node=MASTER
  routerservice:
    privileged: true
    image: registry.onesaitplatform.com/onesaitplatform/router:{{ onesait_version }}
    environment:
      SERVER_NAME: {{ fqdn_server_name }}
    stdin_open: true
    volumes:
    - {{ root_directory }}/onesaitplatform/platform-logs:/var/log/platform-logs:rw
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: node=MASTER
  realtimedb:
    privileged: true
    image: registry.onesaitplatform.com/onesaitplatform/realtimedb:{{ mongo_version }}
    stdin_open: true
    volumes:
    - {{ root_directory }}/onesaitplatform/realtimedb:/data/db:rw
    tty: true
    ports:
    - 27017:27017/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: node=MASTER
