---

- name: Copy nginx.conf
  template: src=nginx.conf dest={{ root_directory }}/onesaitplatform/nginx/nginx.conf

- name: Set repos
  command: yum --enablerepo=extras install epel-release

- name: Install pip
  command: yum -y install python-pip

- name: Install pexpect
  pip:
    name: pexpect
  become: yes

- pause:
    minutes: 3

- name: Login to Rancher
  expect:
    command: rancher config
    responses:
      (?i)URL: "http://{{ fqdn_server_name }}:8080/"
      (?i)Access Key: "{{ rancher_access_key }}"
      (?i)Secret Key: "{{ rancher_secret_key }}"

- name: Create OnesaitPlatform environment
  command: rancher environment create OnesaitPlatform

- name: Remove Default environment
  command: rancher environment rm Default

- name: Install httplib2
  package:
      name=python-httplib2
      update_cache=yes

- name: Get the OnesaitPlatform project id
  uri:
      method: GET
      status_code: 200
      url: http://{{ fqdn_server_name }}:{{ rancher_port }}/v1/projects
      return_content: yes
  register: project_id

- debug: var=project_id.json['data'][0]['id']

- name: Set rancher host registration URL
  uri:
      method: POST
      status_code: 201
      url: http://{{ private_fqdn_server_name }}:{{ rancher_port }}/v1/projects/{{ project_id.json['data'][0]['id'] }}/registrationTokens
      body_format: json
      body: '{"description":"OnesaitPlatform","name":"OnesaitPlatform"}'
      user: "{{ rancher_access_key }}:{{ rancher_secret_key }}"
      headers:
        Content-Type: "application/json"

- pause:
    minutes: 1

- name: Return the registration token URL of Rancher server
  uri:
      method: GET
      status_code: 200
      url: http://{{ fqdn_server_name }}:{{ rancher_port }}/v1/registrationtokens?projectId={{ project_id.json['data'][0]['id'] }} 
      return_content: yes
  register: rancher_token_url  

- debug: var=rancher_token_url.json.data[0]['token']

- name: Execute the docker command
  command: sudo docker run -e CATTLE_AGENT_IP={{ private_fqdn_server_name }} -e CATTLE_HOST_LABELS='NODE%20=MASTER'  --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.11 http://{{ private_fqdn_server_name }}:{{ rancher_port }}/v1/scripts/{{ rancher_token_url.json.data[0]['token'] }}

- name: Copy OnesaitPlatform docker-compose.yml
  template: src=docker-compose.yml dest={{ platform_compose_path }}/docker-compose.yml

- pause:
    minutes: 2

- name: Deploy platform services
  command: rancher --url http://{{ private_fqdn_server_name }}:{{ rancher_port }} --access-key {{ rancher_access_key }} --secret-key {{ rancher_secret_key }} --env OnesaitPlatform stacks create OnesaitPlatform --docker-compose {{ platform_compose_path }}/docker-compose.yml --start=false
