security.ignored: /**

management.security.enabled: false

## Config Web Server
server:
   port: 19300
   contextPath: /digitaltwinbroker
spring:
  application.name: onesaitplatform-digitaltwin-broker
  datasource:
    url: jdbc:mysql://localhost:3306/onesaitplatform_config?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&autoReconnect=true
    username: root
    password: changeIt!
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      # Number of ms to wait before throwing an exception if no connection is available.
      max-wait: 10000
      # Maximum number of active connections that can be allocated from this pool at the same time.
      max-active: 50
      validation-query: SELECT 1
      # Validate the connection before borrowing it from the pool.
      test-on-borrow: true
      test-while-idle: true
    jpa:
      # The SQL dialect makes Hibernate generate better SQL for the chosen database
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      # Hibernate ddl auto (create, create-drop, validate, update)
      hibernate.ddl-auto: validate
  boot.admin: #Spring Boot Admin Config    
    url: http://localhost:18100
    username: operations
    password: changeIt!
    client.metadata.user.name: ${spring.boot.admin.username}
    client.metadata.user.password: ${spring.boot.admin.password} 
    
onesaitplatform: #Config onesaitplatform specific
  digitaltwin.broker:
      rest:
        enable: true
        swaggerhost: localhost:19300   
  database.mongodb:
    database: onesaitplatform_rtdb
    authenticationDatabase:  #admin
    servers: localhost:27017
    autoConnectRetry: true
    socketTimeout: 5000
    maxAutoConnectRetryTime: 5000
    maxWaitTime: 5000
    useAuth: false
    username: #username
    password: #password
    readFromSecondaries: false
    queries.executionTimeout: 5000
    queries.defaultLimit: 1000
    queries.maxConcurrentQueries: 3
    writeConcern: UNACKNOWLEDGED
    tools.mongoexport.path: mongoexport
    tools.mongoimport.path: mongoimport
    tools.mongoshell.path: mongo
    tools.useSequentialOps: true 
  router.alternativeURL: http://localhost:20000/router/router/
        
## LOGGING CONF
logging:
   path: ./target/ 
   file: ${spring.application.name}
   level:
      com.minsait: DEBUG   
  